---
title: "Final Project 134"
author: "Fion, Jessica, Dulce, Yikai"
date: "2025-02-27"
output:
    html_document:
      toc: true
      toc_float: true
      code_folding: show
editor_options: 
  markdown: 
    wrap: sentence
---
# Introduction


# Data Description


# Methodology


# Project Road Map


# Exploring Our Data


## Loading Packages
```{r}
library(tidyverse)
library(dplyr)


```

## Loading in the Dataset
```{r}
# load the data set
amazon <- read.csv("data/amazon.csv")
```


## Exploring Raw Data
```{r}
summary(amazon)
colSums(is.na(amazon))
```

## Tidying the Data
```{r}
# Mutate character variables into numeric
amazon$discounted_price <- as.numeric(gsub("[^0-9.]", "", amazon$discounted_price))
amazon$actual_price <- as.numeric(gsub("[^0-9.]", "", amazon$actual_price))
amazon$discount_percentage <- as.numeric(gsub("[^0-9]", "", amazon$discount_percentage))
amazon$rating_count <- as.numeric(gsub("[^0-9.]", "", amazon$rating_count))

# Find non-numeric rating values
print(amazon$rating[grepl("[^0-9.]", amazon$rating)])

amazon <- amazon %>% 
  filter(grepl("^[0-9.]", rating)) %>% 
  filter(!is.na(rating_count)) %>% 
  mutate(rating = as.numeric(rating))

# Confirm no missing
colSums(is.na(amazon))
```

posssible pca, nlp usage

```{r}
summary(amazon)
```

## Visual EDA

#